spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=anime
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
application:
  specifications:
    query_param: ${APPLICATION_SPECIFICATIONS_QUERY_PARAM:NULL}
