version: '3.1'

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - webflux_data:/var/lib/postgresql/data

volumes:
  webflux_data: